### ISSUE TITLE
Add support for additional stage libraries

### ISSUE THREAD

**Issue by gschmutz** [streamsets/datacollector-docker#6]
Hi

Was just wondering if you would be interested to include support for adding additional stage libraries to your Dockerfile, similar to what I have described in my blog article: https://guidoschmutz.wordpress.com/2016/10/25/additional-stage-libraries-with-dockerized-streamsets/

it basically just involves using a build as well as a runtime variable, to offer to add stage libraries either at build or at runtime. 

Thanks
Guido

**Comment by kunickiaj** [comment]
Hey yeah, that would be useful for folks wanting to build their own image (instead of using a shared data volume for stage libs).

Feel free to open a PR with a patch if you've signed the [CLA](https://streamsets.com/contributing/).

To clarify the currently intended usage here's an example:

To install stage libs using the CLI or Package Manager UI you'll need to create a volume for the stage libs directory. It's also recommended to use a volume for the data directory at a minimum.

```
docker volume create --name sdc-stagelibs
docker volume create --name sdc-data
```

The volume needs to then be mounted to the correct directory when launching the container.

```
docker run --name sdc -d -v sdc-stagelibs:/opt/streamsets-datacollector-2.1.0.2/streamsets-libs -v sdc-data:/data -P streamsets/datacollector dc -verbose
```

To get a list of available libs you could do:

```
docker run --rm streamsets/datacollector:2.1.0.2 stagelibs -list
```

To install say, the JDBC lib to the sdc-stagelibs volume you created above, you would run:

```
docker run --rm -v sdc-stagelibs:/opt/streamsets-datacollector-2.1.0.2/streamsets-libs streamsets/datacollector:2.1.0.2 stagelibs -install=streamsets-datacollector-jdbc-lib
```

This lets you create a single stagelibs volume that can be shared among containers--it's the best way to use the "official" container without using a custom image. However, a custom image certainly is simpler to use.
